### ISSUE TITLE
Scrollbars didn't change after installation

### ISSUE THREAD

**Issue by abrac** [rafaelmardojai/firefox-gnome-scrollbars#11]
Hi @rafaelmardojai. How can I change the color of the scrollbars to match the dark theme of gnome? Is there a place in the code where the color is assigned?

#### Screenshot of what I want:
![screenshot of what I want][1]

EDIT: I see that there are dark scrollbars in `about:preferences`. But not in normal websites...

EDIT 2: I found a [place in the code][2] where the RGB values for a dark colorscheme are stored... How can I use these in normal websites? I'm not familiar with Javascript.

[1]: https://user-images.githubusercontent.com/55248999/99226107-e0613280-27f1-11eb-8b60-6e2711032152.png
[2]: https://github.com/rafaelmardojai/firefox-gnome-scrollbars/blame/master/user_chrome/gnome-scrollbars.uc.js#L16-L26

**Comment by rafaelmardojai** [comment]
What do you mean in normal websites? Implementing custom scrollbars with GNONE style in a website?

**Comment by abrac** [comment]
Sorry, by *normal websites*, I mean websites besides `about:preferences`. 

I have installed firefox-gnome-scrollbars in Firefox, but the scrollbars have a light theme. I want the scrollbars to have a dark theme. They appear dark in `about:preferences` but in all other websites they are light.

**Comment by abrac** [comment]
Maybe the image below makes my question more clear. When I installed firefox-gnome-scrollbars, I got dark scrollbars in `about:preferences`. But in all other websites, the scrollbars have a light color scheme. I want to change the color scheme of those scrollbars to be dark. 

![image](https://user-images.githubusercontent.com/55248999/99293724-b177aa80-284b-11eb-88e9-e52c8ff29afb.png)

**Comment by rafaelmardojai** [comment]
**firefox-gnome-scrollbars** is supposed to work fine in all websites, scrollbars are also overlayed like native GTK ones, and that also don't seem to happen in your screenshot.

**Comment by rafaelmardojai** [comment]
Right now I'm using Firefox flatpak, so I'm not using firefox-gnome-scrollbars (there's no way to install it). Maybe a recent firefox update has broken it, so I need to test it.

**Comment by abrac** [comment]
Oh, I see. I honestly thought these scrollbars were GTK ones. (I'm sure they were more rectangular before I installed firefox-gnome-scrollbars 🤔). I will try install it again on another computer and see if it works.

**Comment by rafaelmardojai** [comment]
Firefox already have GTK styled scrollbars, but they don't respect the dark theme and are not overlayed.

**Comment by abrac** [comment]
Okay, I understand now! Thank you for clarifying! I'll try install it on another computer and will let you know how it goes.

**Comment by abrac** [comment]
@rafaelmardojai  I figured out the problem! The problem was with the install script. [These lines][1] failed to locate my Firefox profile's path. I just manually assigned my profile to the `FFPROFILE` variable, and everything worked fine. 

Thank you for you patience and help. These scrollbars look *really* slick! 

[Screenshot][2] (for future visitors who are curious)

[1]: https://github.com/rafaelmardojai/firefox-gnome-scrollbars/blob/master/install.sh#L8-L13
[2]: https://user-images.githubusercontent.com/55248999/99589344-84b2c700-29f4-11eb-8951-e03f5feb1ba1.png

**Comment by rafaelmardojai** [comment]
Nice to know. 

Would be good to port the latest changes from firefox-gnome-theme install script. But currently I don't have time.

**Comment by abrac** [comment]
Okay, no problem. Just for future reference: It turns out that the install script is actually fine. The problem might be with my `profiles.ini` file.

Below is a snippet from my `profiles.ini` file... The profile that I am using is *Chris* (Profile 0). But the script returns *Uncynced* (Profile 1) as `$FFPROFILE`. Not sure if my `profiles.ini` file is messed up somehow.

```
[Install4F96D1932A9F858E]
Default=gb1dvwz8.Chris-1593800949774
Locked=1

[Profile1]
Name=Unsynced
IsRelative=1
Path=uryap4xm.default
Default=1

[Profile0]
Name=Chris
IsRelative=1
Path=gb1dvwz8.Chris-1593800949774
```

**Comment by rafaelmardojai** [comment]
> The problem might be with my profiles.ini file.

Yes, and that's quite common. That's why firefox-gnome-theme now uses a different method.
