### ISSUE TITLE
Thunderbird Support

### ISSUE THREAD

**Issue by 73** [rafaelmardojai/firefox-gnome-scrollbars#9]
Since Thunderbird is based on Firefox, this might work in Thunderbird, too.
I tried to follow install procedure and replace the Firefox specific folders with Thunderbird folders. It did not work, but I did not see an error in Error Console either. 

It would be nice to have beautiful scrollbars in Thunderbird, too.

**Comment by rafaelmardojai** [comment]
I don't use Thunderbird. But later i will install it and see what I can do!

**Comment by rafaelmardojai** [comment]
I couldn't make it work. 

Probably some functions used by the JS loader (`user_chrome/utils`) are Firefox only.

**Comment by 73** [comment]
Thanks for trying, anyway. I really appreciate it.

**Comment by 73** [comment]
Support is not needed. [This](https://github.com/rafaelmardojai/firefox-gnome-scrollbars/issues/3#issuecomment-979773152) works in Thunderbird.
